modLoader="javafml"
loaderVersion="[47,)"
license = "MIT"

[[mods]]
modId="fnc"
version="1.2.1"
displayName="Factions And Curiosities"
logoFile="factions_and_curiosities.png"
credits="Thanks to Fhyx for creating some of the textures! Also thanks to Ceddi and Nico for helping with testing and balancing."
authors="Joh0210"
description='''
A mod that expands the world of magic to include additional factions!
'''

[[dependencies.fnc]]
modId="forge"
mandatory=true
versionRange="[47.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.fnc]]
modId="mna"
mandatory=true
versionRange="[3.0.0.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.fnc]]
modId="curios"
mandatory=true
versionRange="[5.4.7,)"
ordering="NONE"
side="BOTH"

[[dependencies.fnc]]
modId="dmnr"
mandatory=false
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fnc]]
modId="geckolib"
mandatory=true
versionRange="[4.2.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.fnc]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"