modLoader = "javafml"
loaderVersion = "[34,)"
license = "MIT"
[[mods]]
modId="fnc"
version="${file.jarVersion}"
displayName="Factions And Curiosities"
logoFile="factions_and_curiosities.png"
credits="Thanks to Fhyx for creating some of the textures! Also thanks to Ceddi and Nico for helping with testing and balancing."
authors="Joh0210"
description='''
A mod that expands the world of magic to include additional factions!
'''

[[dependencies.fnc]]
modId="forge"
mandatory=true
versionRange="[43.2.23,)"
ordering="NONE"
side="BOTH"

[[dependencies.fnc]]
modId="mna"
mandatory=true
versionRange="[2.1.0.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.fnc]]
modId="curios"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.fnc]]
modId="geckolib3"
mandatory=true
versionRange="[forge-3.1.40,)"
ordering="NONE"
side="BOTH"

[[dependencies.fnc]]
modId="dmnr"
mandatory=false
versionRange="[1.19.2-3.0.4,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fnc]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"