modLoader = "javafml"
loaderVersion = "[34,)"
license = "MIT"
[[mods]]
modId="fnc"
version="${file.jarVersion}"
displayName="Factions And Curiosities"
logoFile="factions_and_curiosities.png"
credits="Thanks to Mithion for helping creating some code elements of this mod! Also thanks to Ceddi and Nico for helping with testing and balancing."
authors="Joh0210"
description='''
A mod that expands the world of magic to include additional factions!
'''


[[dependencies.fnc]]
modId="forge"
mandatory=true
versionRange="[40.1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.fnc]]
modId="mna"
mandatory=true
versionRange="[2,)"
ordering="NONE"
side="BOTH"

[[dependencies.fnc]]
modId="dragonmagicandrelics"
mandatory=false
versionRange="[1.18.2-2.1.25,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fnc]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"